apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: fleetuser
rules:
 - apiGroups:
     - fleet.cattle.io
   resources:
     - gitrepos
   verbs:
     - get
     - list
     - create
     - delete